name: Build & Conditional Release

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Check if commit is tagged and on main
        id: tag_check
        run: |
          IS_MAIN=$([[ "$GITHUB_REF_NAME" == "main" ]] && echo true || echo false)
          TAG=$(git tag --points-at HEAD)
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT
          echo "on_main=$IS_MAIN" >> $GITHUB_OUTPUT

      - name: Get commit logs since last tag
        if: steps.tag_check.outputs.on_main == 'true' && steps.tag_check.outputs.tag_name != ''
        id: changelog
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -n "$PREV_TAG" ]; then
            LOG=$(git log "$PREV_TAG"..HEAD --pretty=format:"- %s (%an)")
          else
            LOG=$(git log HEAD --pretty=format:"- %s (%an)")
          fi
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$LOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        if: steps.tag_check.outputs.on_main == 'true' && steps.tag_check.outputs.tag_name != ''
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_check.outputs.tag_name }}
          name: ${{ steps.tag_check.outputs.tag_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          files: app/build/outputs/apk/release/app-release.apk
